# Generated by Django 2.2.9 on 2020-01-31 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_product_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_detail',
            name='img',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
    ]
