# Generated by Django 2.2.9 on 2020-01-31 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_product_detail_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_detail',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
