# Generated by Django 2.2.9 on 2020-01-31 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200131_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_detail',
            name='details',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
