# Generated by Django 2.2.9 on 2020-02-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_checkout_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout_detail',
            name='order',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='checkout_detail',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
